<a href="https://colab.research.google.com/github/itzelreveles/unidad-1/blob/main/Practica_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Itzel America Reveles Martinez -24 de septiembre de 2025
practica 6- cortar arreglos numpy

---------------------------------------------------
slice en python  significa tomar elemntos de unindice determinado a corto determinando indice.

Pasamos en sline en lugar del inidce de sta mnera :[start:end]
si no apasamos el inicio se concidera un 0
s in o pasamos el final, su longitud es condicderadaras una matriz de una dimension
----
ejemplo:([1,2,3,4,5,6,7])
cortar los elemntos de indice 1 al idice 5

In [1]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[1:5])

[2 3 4 5]


ejemplo 2; ([1,2,3,4,5,6,7)] cortar del indice 4 hasta el final de la matriz

In [2]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[4:])

[5 6 7]


Ejemplo 3:
([1,2,3,4,5,6,7])
cortar elemntos desde el indice 5

In [3]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[:5])

[1 2 3 4 5]


Ejemplo 4:
([1,3,4,5,6,7)]
corte negativo. Utilizamos el operador "-" para hacer referencia a un idice desde el final.

-------------------
Cortar del indice 3 al final al indice 1 desde el final.

In [4]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[-3:-1])

[5 6]
