<a href="https://colab.research.google.com/github/itzelreveles/unidad-1/blob/main/Practica7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Itzel America Reveles Martinez - Practica7 -25 de septiembre 2025.
---------------------------------------------
Slicing NumPy
---------------------------------------------
Utilice STEP para determinar el paso del corte:
Ejemplo: ([1,2,3,4,5,6,7]) - Devuelve todos los elemntos del indice 1 al indice 5


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


Ejemplo 2: ([1,2,3,4,5,6,7])
Devuelve los elemntos de la matriz
---------------------------


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


Slice de matrices 2D
----------------------
Ejemplo:([1,2,3,4,5], [6,7,8,9,10])
Del segundo elemento, corte del indice 1 al inidce 4.

In [6]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


Ejemplo4: ([[1,2,3,4,5], [6,7,8,9,10]])
De ambos elementos, devuelve el indice 2
------------------------------------


In [7]:
import numpy  as  np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])
#

[3 8]


Ejemplo5: ([[1,2,3,4,5], [6,7,8,9,10]])
De ambos elemntos corta el indice 1 al indice 4.

In [8]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])
#

[[2 3 4]
 [7 8 9]]


Ejercicio1 - Autonomo
Del siguiente arreglo, Caul es el resultado?
([1,2,3,4,5,6,7])
Corta del 1er elemento al 6to elemento con paso 2

In [10]:
import numpy  as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[0:6:2])
#

[1 3 5]
